language: node_js
node_js:
  - 10
cashe: npm
before_install:
  - 'nvm install-latest-npm'
sudo: false
script:
  - npm install
  - npm run test
  - export NODE_OPTIONS=--max_old_space_size=4096
  - npm run build
before_deploy:
  - TRAVIS_TAG=v`node -pe "require('./package.json').version"`
  - zip -r bts-ce-web-${TRAVIS_TAG}.zip build/*
deploy:
      provider: releases
      api_key: $GH_TOKEN
      file: 
        - bts-ce-web-${TRAVIS_TAG}.zip
      draft: true
      skip_cleanup: true
      overwrite: true
      on:
        tag_name: $TRAVIS_TAG
        branch: master
branches:
  only:
    - master

