language: node_js
node_js:
  - 10
branches:
  only:
    - master
cashe: npm
before_install:
  - 'nvm install-latest-npm'
sudo: false
script:
  - npm install
  - npm run test
  - export NODE_OPTIONS=--max_old_space_size=4096
  - npm run build
before_deploy:
  - TRAVIS_TAG=`node -pe "require('./package.json').version"`
  - DRAFT_TAG=v$TRAVIS_TAG
  - zip -r bts-ce-web-${TRAVIS_TAG}.zip build/*
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 
    - bts-ce-web-${TRAVIS_TAG}.zip
  tag_name: $DRAFT_TAG
  target_commitish: $TRAVIS_BRANCH
  name: $DRAFT_TAG
  draft: true
  skip_cleanup: true
  overwrite: true
  on:
    branch: "master"

        